name: Test Publish On PR

on:
    pull_request:
        branches:
            - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    - run: npm run package
    - run: npm run build
    - run: npm publish --dry-run
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}